### ISSUE TITLE
我们为什么能用中文命名,加上文言文不是更牛逼

### ISSUE THREAD

**Issue by aixi2494** [menzi11/BullshitGenerator#102]
interface 幼小离家 {
    interface V层 {
        fun 偷拿地主余粮(时间: IncomeMonth?)
    }

    interface P层 {
        fun 无以为食(时间: String)

        fun 去地主家(v: V层)
    }
}

**Comment by aixi2494** [comment]
`interface 幼小离家 {
    interface V层 {
        fun 偷拿地主余粮(时间: IncomeMonth?)
    }

    interface P层 {
        fun 无以为食(时间: String)

        fun 去地主家(v: V层)
    }
}
`

**Comment by zysNLP** [comment]
我们为什么能用中文命名,加上文言文不是更牛逼的发生，到底需要如何做到，不我们为什么能用中文命名,加上文言文不是更牛逼的发生，又会如何产生。 达·芬奇在不经意间这样说过，大胆和坚定的决心能够抵得上武器的精良。这启发了我， 我们一般认为，抓住了问题的关键，其他一切则会迎刃而解。 本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 在这种困难的抉择下，本人思来想去，寝食难安。 那么， 既然如何， 所谓我们为什么能用中文命名,加上文言文不是更牛逼，关键是我们为什么能用中文命名,加上文言文不是更牛逼需要如何写。 既然如何， 我们为什么能用中文命名,加上文言文不是更牛逼，到底应该如何实现。 笛卡儿在不经意间这样说过，阅读一切好书如同和过去最杰出的人谈话。这不禁令我深思。 一般来讲，我们都必须务必慎重的考虑考虑。 一般来说， 每个人都不得不面对这些问题。 在面对这种问题时， 既然如何， 就我个人来说，我们为什么能用中文命名,加上文言文不是更牛逼对我的意义，不能不说非常重大。 生活中，若我们为什么能用中文命名,加上文言文不是更牛逼出现了，我们就不得不考虑它出现了的事实。 我们一般认为，抓住了问题的关键，其他一切则会迎刃而解。 本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 生活中，若我们为什么能用中文命名,加上文言文不是更牛逼出现了，我们就不得不考虑它出现了的事实。 我们为什么能用中文命名,加上文言文不是更牛逼，到底应该如何实现。 就我个人来说，我们为什么能用中文命名,加上文言文不是更牛逼对我的意义，不能不说非常重大。 既然如此， 这样看来， 一般来说， 我们都知道，只要有意义，那么就必须慎重考虑。 文森特·皮尔说过一句富有哲理的话，改变你的想法，你就改变了自己的世界。这不禁令我深思。 我们不得不面对一个非常尴尬的事实，那就是， 那么， 既然如此， 本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 所谓我们为什么能用中文命名,加上文言文不是更牛逼，关键是我们为什么能用中文命名,加上文言文不是更牛逼需要如何写。 所谓我们为什么能用中文命名,加上文言文不是更牛逼，关键是我们为什么能用中文命名,加上文言文不是更牛逼需要如何写。 在这种困难的抉择下，本人思来想去，寝食难安。

**Comment by aixi2494** [comment]
牛皮

**Comment by aixi2494** [comment]
牛皮
