### ISSUE TITLE
想问问不使用英文输入法，中文符号怎么转换成英文符号的？

### ISSUE THREAD

**Issue by Niefee** [menzi11/BullshitGenerator#104]
如题。

**Comment by nobodxbodon** [comment]
是指在代码中用中文命名如何切换到英文标点吗？
输入法可以设置“中文输入下使用英文标点”。还可以指定 app，比如设置仅限于在 IDE 中。

**Comment by Niefee** [comment]
刚刚试了一下，原来还有这个功能。

**Comment by menzi11** [comment]
在大部分输入法里可以修改"中文时使用英文标点". 我这么用好多年了....
