### ISSUE TITLE
什么时间可以进化到能够取代我写文章，至少我的公众号每天的原创有着落了！

### ISSUE THREAD

**Issue by xmt1139057136** [menzi11/BullshitGenerator#108]
什么时间可以进化到能够取代我写文章，至少我的公众号每天的原创有着落了！

![image](https://user-images.githubusercontent.com/23303979/68842757-e5346780-0701-11ea-9332-4250168ad3eb.png)

到这一天，我相信不少媒体工作者都要丢饭碗了！

**Comment by menzi11** [comment]
在可预见的未来暂时不需要担心哈, 只是拿来搞笑的
