### ISSUE TITLE
我们同事用这个提交了心得，被公开处刑了

### ISSUE THREAD

**Issue by ifansay** [menzi11/BullshitGenerator#182]
哈哈哈

**Comment by hmsjy2017** [comment]
这都敢...

**Comment by mesondzh** [comment]
你同事也是个奇才😂

**Comment by PRO-2684** [comment]
还健在吗？🤣

**Comment by liux-pro** [comment]
哈哈哈哈哈哈哈哈哈哈或或

**Comment by 00LT00** [comment]
各位都是人才，我打算拿这个水水学校让交的报告哈哈哈

**Comment by zhiyuanzhai** [comment]
我觉得吧……
这个小东西毕竟不算严谨
貌似也没有引进神经网络或者什么高级算法
拿来搞笑还好
真要拿来交个差
万一有人看到
会出人命的……

如果有人真想拿这玩意交差
请你提交一个pull request
用点高端的东西
再试试效果吧

**Comment by hmsjy2017** [comment]
作者都说了不能用于正规用途，只能用来搞笑

**Comment by poorsecretary** [comment]
我曾经想过用这个写检讨，居然还有人真的用这个交差的，也是头铁。
