### ISSUE TITLE
建议针对浙江 2020 满分作文更新词库变量

### ISSUE THREAD

**Issue by youknowznm** [menzi11/BullshitGenerator#196]
请参考 [如何评价浙江省2020年高考作文满分范文《生活在树上》？
](https://www.zhihu.com/question/411528513/answer/1379611520)

**Comment by RalapChen** [comment]
感觉比浙江满分作文写得好

**Comment by HE-YANGFAN** [comment]
辣是真的牛批

**Comment by FlyingPig1108** [comment]
以后高考作文范文一键生成
