### ISSUE TITLE
谢谢大佬，我的思修课活跃分就靠这个了

### ISSUE THREAD

**Issue by LavaCreeperh** [menzi11/BullshitGenerator#200]
![-40685afb5a2df74c.jpg](https://user-images.githubusercontent.com/50040800/102852483-52641180-4459-11eb-92ad-9bede4816378.jpg)

**Comment by zhiyuanzhai** [comment]
参见readme:

> 再次声明一下, 本项目生成的文章真的狗屁不通, 只能拿来搞笑, 请不要用于正规用途!

我只能说：壮士，一路走好！

Edit: 不过这个应该确实也没人看……

**Comment by liuup** [comment]
壮士
