### ISSUE TITLE
> nodejs版直接抛弃了得了,只留网页版,或者写一个nodejs和浏览器兼容的版本.需要考虑浏览器怎么加载json.

### ISSUE THREAD

**Issue by ghost** [menzi11/BullshitGenerator#214]
> nodejs版直接抛弃了得了,只留网页版,或者写一个nodejs和浏览器兼容的版本.需要考虑浏览器怎么加载json.

网页版可以直接用Ajax请求加载JSON文件,NodeJS和Web无法兼容

_Originally posted by @jingyuexing in https://github.com/menzi11/BullshitGenerator/issues/19#issuecomment-549098346_

**Comment by FlyingPig1108** [comment]
信件已收悉！祝好！张圣泽
