### ISSUE TITLE
readJSON是什么模块

### ISSUE THREAD

**Issue by dnslin** [menzi11/BullshitGenerator#41]
没用过这个模块 pip导入不了

**Comment by hldh214** [comment]
https://github.com/menzi11/BullshitGenerator/blob/master/readJSON.py

**Comment by jingyuexing** [comment]
原作者来说明一下，这个是我自己写的模块，用来读取JSON文件,将读取到的文件直接转化为对象,在***NodeJS***当中它会执行后返回一个`Object`其实就是`JSON数据`，而在***Python***当中会将读取到的`JSON`文件转化为字典`dict`并返回

**Comment by blankmiss** [comment]
谢谢指导 新学的python 看到这么有趣的项目（大佬牛皮）

**Comment by anna-mo** [comment]
噗，新学代码参照这个风格发展，表示期待~
